name: MythicMobs-Time
version: 1.1.0
main: dev.genzstore.mythicmobstime.MythicMobsTime
api-version: 1.20
description: Auto boss spawning system for Minecraft servers with MythicMobs
author: GenzStore
website: https://genzstore.dev

depend: [MythicMobs]
softdepend: [PlaceholderAPI]

commands:
  mmtime:
    description: Main command for MythicMobs-Time
    usage: /mmtime <reload|list|force|remove>
    permission: mythicmobstime.admin

permissions:
  mythicmobstime.*:
    description: All permissions for MythicMobs-Time
    children:
      mythicmobstime.admin: true
      mythicmobstime.notify: true

  mythicmobstime.admin:
    description: Admin permissions for MythicMobs-Time
    default: op